NodeVersion="24.13.0"
nodeBuildCommandsFile="/tmp/zipdeploy/extracted/oryx-build-commands.txt"
Frameworks="Next.js"
compressedNodeModulesFile="node_modules.tar.gz"
OutputDirPath=".next"
OperationId="ec8b68da8cb58ca2"
SourceDirectoryInBuildContainer="/tmp/8de6e165718f5f4"
PlatformName="nodejs"
CompressDestinationDir="false"
